/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

//import com.sun.awt.AWTUtilities;
import ClassStatic.Log;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.edisoncor.gui.util.WindowsUtil;


/**
 *
 * @author Eudy
 */
public class splash extends javax.swing.JFrame implements Runnable {


    Thread hilo;
    private int cont=9;
    private conexion.Mysql mysql;
    /**
     * Creates new form splash
     *
   
    public splash() {
        initComponents();
        //AWTUtilities.setWindowOpaque(this, false);
        this.setLocationRelativeTo(null);
         this.scalarImagen();
    }*/
   
    public splash(conexion.Mysql mysql){
             initComponents();
             this.setLocationRelativeTo(null);
         try{
             if( (mysql != null) )
        {
            this.mysql = mysql;

            System.out.println(getClass().getResource("../icono/logovyr.gif"));
            
            this.setIconImage(new ImageIcon("C:/app_vyr/img/iconoclinica.gif").getImage());
            //setIconImage(new ImageIcon(getClass().getResource("../icono/logovyr.gif")).getImage());
            
           // @SuppressWarnings("unchecked") Class awtutil = Class.forName("com.sun.awt.AWTUtilities");
            //com.sun.awt.AWTUtilities.setWindowOpaque(this, false);
            
            this.scalarImagen();
            //JOptionPane.showMessageDialog(null, " objeto mysql Splash");
            this.getContentPane().setBackground(new Color(255,255,255,255));
            //this.setOpacity(0.0f);
        }
            
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, "Mal Splash "+e);
        }
       
    }

    public void scalarImagen(){      
        Log.Registrar(this.getClass(), "scalarImagen", "");

           //JOptionPane.showMessageDialog(null, splash.class.getResource("../"));
        try{
            this.checkImg("2");
         }catch(Exception e){
             this.checkImg("2");
            //JOptionPane.showMessageDialog(null, "scale Splash "+e);
        }
    }
    public void checkImg(String opcion){       
        Log.Registrar(this.getClass(), "checkImg", "");

        switch(opcion){
            case "1":
                ImageIcon  img = new ImageIcon(splash.class.getResource("../icono/iconoclinica.gif"));
                Icon imgIco = new ImageIcon(img.getImage().getScaledInstance(this.jLabel1.getWidth(), this.jLabel1.getHeight() ,Image.SCALE_DEFAULT));
                this.jLabel1.setIcon(imgIco);
              break;
            case "2":
                ImageIcon  img1 = new ImageIcon("C:/app_vyr/img/iconoclinica.gif");
                Icon imgIco1 = new ImageIcon(img1.getImage().getScaledInstance(this.jLabel1.getWidth(), this.jLabel1.getHeight() ,Image.SCALE_DEFAULT));
                this.jLabel1.setIcon(imgIco1);
              break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, -1, 40));

        jProgressBar1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jProgressBar1StateChanged(evt);
            }
        });
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 800, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jProgressBar1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jProgressBar1StateChanged
        // TODO add your handling code here:
                double resta =100 - this.jProgressBar1.getValue();
                double division = resta / 100;
                float  v = (float) division ;
                //double v = double.valueOf() )+"");
                //System.out.println(division+" "+resta+" "+v);
                WindowsUtil.makeWindowsOpacity(this,v);
                
    }//GEN-LAST:event_jProgressBar1StateChanged

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {       
        Log.Registrar(this.getClass(), "run", "");

        
        try {
            Log.Registrar("Inicio el splash");
            this.setVisible(true);
            for(int i = 0 ; i < 100 ; i++){
                this.jProgressBar1.setValue(i);
                this.jLabel2.setText(i+"%");
                hilo.sleep(60);
            }
        } catch (InterruptedException ex) {
            Log.Error("Splash ", ex);
            Logger.getLogger(splash.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        Log.Registrar("Termino el splash");
        new login_f(this.mysql).setVisible(true);
    }
}
