/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios.Conduce;

import ClassStatic.Log;
import Render.RenderListaReparaciones;
import conexion.Mysql;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VOSTRO
 */
public class ListadoReparacionesCompleta extends javax.swing.JFrame {

    /**
     * Creates new form ListadoReparacionesCompleta
     */
        private Mysql mysql;
        private String nombreUsuario = "";
        private String UsuarioID="1";
        private java.sql.ResultSet resultSet;
        private int totalR = 0; 
        
        
    public ListadoReparacionesCompleta(Mysql mysql) {
        initComponents();
        this.jPanel1.setBackground(Color.red);//this.getContentPane().setBackground(Color.white);
        this.mysql = mysql;
    }
    public void setTotalR(int totalR){
        this.totalR = totalR;
    }
    

    public void setResultSet(ResultSet resultSet) {
        this.resultSet = resultSet;
    }
    
    public void setDatosUsuario(String nombre,String id){
        this.nombreUsuario = nombre;
        this.UsuarioID = id;
        System.out.println(nombre+" "+id);
    }
    
    public void cargarTabla(){        
        Log.Registrar(this.getClass(), "cargarTabla", "");

        try {
        String[] titulos = {"USUARIO","CLIENTE","NO.CONDUCE","A DURADO (DIAS)", "SUB TOTAL","ITBIS","MONTO","MONTO ABONO","NOTA","ESTADO"};
        
        Object[][] fila = new Object[this.totalR][10];
            
        this.resultSet.first();
         int c = 0;
         
          do{
                fila[c][3] = this.resultSet.getString("dias");
                    fila[c][2] = this.resultSet.getString("id");
                    fila[c][4] = this.resultSet.getString("sub_total");
                    fila[c][9] = this.resultSet.getString("estado");
                    fila[c][8] = this.resultSet.getString("nota");
                    fila[c][7] = this.resultSet.getString("abono");
                    fila[c][5] = this.resultSet.getString("itbis");
                    fila[c][6] = this.resultSet.getString("total");
                    fila[c][1] = this.resultSet.getString("nombrecompleto");
                    fila[c][0] = this.resultSet.getString("nombre_usuario");
                            
                    c++;
             } while(this.resultSet.next());
          DefaultTableModel modelo = new DefaultTableModel(fila,titulos);
          this.jTable1.setModel(modelo);
          this.jTable1.setDefaultRenderer(Object.class, new RenderListaReparaciones());
        } catch (SQLException ex) {
            Log.Error(this.getClass().getName(), ex);
                Logger.getLogger(ListadoReparacionesCompleta.class.getName()).log(Level.SEVERE, null, ex);
          }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de reparaciones");
        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
